from yacs.config import CfgNode as CN


_C = CN()

# Model
_C.MODEL = CN()

# dataset
_C.DATASET = CN()
_C.DATASET.DATA_ROOT = "/home/storage/sde_2T"

_C.DATASET.TRAIN = CN()
_C.DATASET.TRAIN.IMG_PREFIX = "NIA/SEN"
_C.DATASET.TRAIN.ANN_FILE = "NIA/KSL_sen_train.csv"

_C.DATASET.VAL = CN()
_C.DATASET.VAL.IMG_PREFIX = "NIA/SEN" 
_C.DATASET.VAL.ANN_FILE = "NIA/KSL_sen_val.csv"

_C.DATASET.WORKER_PER_GPU = 16

# transform parameters
_C.DATASET.TRANSFORM = CN()

# Resize
_C.DATASET.TRANSFORM.RESIZE_IMG = (256, 256)  # (H, W)
_C.DATASET.TRANSFORM.TEMPORAL_SCALING = 1.0

# Crop
_C.DATASET.TRANSFORM.CROP_SIZE = (224, 224)
_C.DATASET.TRANSFORM.TEMPORAL_CROP_RATIO = 0.0

# NORMALIZATION0.1154,0.1051,0.1897
_C.DATASET.TRANSFORM.MEAN = (0.0637, 0.0988, 0.2312)
_C.DATASET.TRANSFORM.STD = (0.0643, 0.0556, 0.1150) 

# Vocabulary
_C.DATASET.VOCABULARY = CN()
#_C.DATASET.VOCABULARY.EXCLUDE_TOKENS = ["__ON__", "__OFF__"]

# solver
_C.SOLVER = CN()
_C.SOLVER.BATCH_PER_GPU = 2
_C.SOLVER.BASE_LR = 1e-4
_C.SOLVER.OPTIM_NAME = "Adam"  # "SGD" or "Adam"
_C.SOLVER.WEIGHT_DECAY_NORM = 0.0
_C.SOLVER.BIAS_LR_FACTOR = 1.0


# SGD params
_C.SOLVER.SGD = CN()
_C.SOLVER.SGD.MOMENTUM = 0.9
_C.SOLVER.SGD.WEIGHT_DECAY = 0.0005
_C.SOLVER.SGD.NESTEROV = True

# Adam params
_C.SOLVER.ADAM = CN()
_C.SOLVER.ADAM.BETA1 = 0.9
_C.SOLVER.ADAM.BETA2 = 0.999
_C.SOLVER.ADAM.EPS = 1e-08
_C.SOLVER.ADAM.WEIGHT_DECAY = 1e-4

# scheduler setup
_C.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
_C.SOLVER.STEPS = (40, 60,)
_C.SOLVER.GAMMA = 0.5   # lr decay factor
_C.SOLVER.RAMPDOWN_ITERS = 0
_C.SOLVER.WARMUP_FACTOR = 0
_C.SOLVER.WARMUP_ITERS = 0
_C.SOLVER.WARMUP_METHOD = "linear"

# Periodical params
_C.PERIODS = CN()
_C.PERIODS.EVAL = 1
_C.PERIODS.CHECKPOINT = 1
_C.PERIODS.LOG_ITERS = 50

# misc
_C.OUTPUT_DIR = "outputs/ksl"
_C.RESUME = ""
_C.GPU_ID = 0
_C.RESUME = "" #"/home/PATH_TO/outputs/ksl/model_best.pth.tar"
_C.NOTE = ""

# Reproducability
_C.SEED = 33
_C.CUDNN_DETERMINISTIC = False
_C.CUDNN_BENCHMARK = True
